myproject/models.py
#setupdb inside __init__ file.

from myproject import db,login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model,UserMixin):
     __tablename__ = 'users'

     id = db.Column(db.Integer,primary_key=True)
     username = db.Column(db.String(64),index=True)
     password_hash = db.Column(db.String(128))

     def __init__(self,username,password):
         self.username = username
         self.password_hash = generate_password_hash(password)

     def check_password(self,password):
         check_password_hash(self.password_hash,password)


class Puppy(db.Model):
    __tablename__ = 'puppies'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    owner = db.relationship('Owner', backref='puppy', uselist=False)

    def __init__(self,name):
        self.name = name

    def __repr__(self):
        if self.owner:
            return f"Puppy name is {self.name} and owner is {self.owner.name}"
        else:
            return f"Puppy name is {self.name} and has no owner yet"

class Owner(db.Model):

    __tablename__ = 'owners'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    puppy_id = db.Column(db.Integer, db.ForeignKey('puppies.id'))

    def __init__(self,name,puppy_id):
        self.name = name
        self.puppy_id = puppy_id

    def __repr__(self):
        return f"owner name is {self.name}"

myproject/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField
from wtforms.validators import DataRequired,EqualTo
from wtforms import ValidationError
from myproject.models import User

class LoginForm(FlaskForm):
    username = StringField("Enter the username:",validators=[DataRequired()])
    password = PasswordField("Password",validators=[DataRequired()])
    submit = SubmitField("Log In")

class RegistrationForm(FlaskForm):
    username = StringField("Username",validators=[DataRequired()])
    password = PasswordField("Password",validators=[DataRequired(),EqualTo('pass_confirm',message='Password must match')])
    pass_confirm = PasswordField("Confirm Password",validators=[DataRequired()])
    submit = SubmitField("Register")

    def check_user(self,field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('This username is already registered')

myproject/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,BooleanField,DateTimeField,RadioField,SelectField,TextAreaField,TextField,IntegerField
from wtforms.validators import DataRequired,Email,EqualTo, Length, ValidationError

class Addowner(FlaskForm):
    name = StringField("Name of owner:",validators=[DataRequired()])
    puppy_id = IntegerField("Enter Puppy Id:",validators=[DataRequired()])
    submit = SubmitField("Submit")

myproject/puppies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,BooleanField,DateTimeField,RadioField,SelectField,TextAreaField,TextField,IntegerField
from wtforms.validators import DataRequired,Email,EqualTo, Length, ValidationError



class Add(FlaskForm):
    name = StringField("Name of pupy",validators=[DataRequired()])
    submit = SubmitField("Submit")

class Del(FlaskForm):
    id = IntegerField("Enter the id:",validators=[DataRequired()])
    submit = SubmitField("Submit")

myproject/__init__.py
import os
from flask import Flask,url_for,redirect,render_template,session

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

from flask_login import LoginManager

login_manager = LoginManager()

app = Flask(__name__)

app.config['SECRET_KEY'] = 'Thisisasecretkey'


# Database config goes here.

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

login_manager.init_app(app)
login_manager.login_view = 'login'

from myproject.puppies.views import puppies_blueprint
from myproject.owners.views import owner_blueprint

app.register_blueprint(puppies_blueprint,url_prefix='/puppies')
app.register_blueprint(owner_blueprint,url_prefix='/owners')

myproject/owners/views.py
from flask import Blueprint,render_template,redirect,url_for
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import Addowner
from flask_login import login_user,login_required,logout_user

owner_blueprint = Blueprint('owners',__name__,template_folder='templates/owners')

@owner_blueprint.route('/add',methods=['GET','POST'])
@login_required
def add():

    form = Addowner()

    if form.validate_on_submit():
        name = form.name.data
        puppyid = form.puppy_id.data
        owner_details = Owner(name,puppyid)
        db.session.add(owner_details)
        db.session.commit()
        return redirect(url_for('puppies.list'))
    return render_template('add_owner.html',form=form)

myproject/puppies/views.py
from flask import Blueprint,render_template,url_for,redirect
from myproject import db
from myproject.models import Puppy
from myproject.puppies.forms import Add,Del
from flask_login import login_user,login_required,logout_user



puppies_blueprint = Blueprint('puppies',__name__,template_folder='templates/puppies')

@puppies_blueprint.route('/add',methods=['GET','POST'])
@login_required
def add():

    form = Add()
    if form.validate_on_submit():
        name = form.name.data
        new_puppy = Puppy(name)
        db.session.add(new_puppy)
        db.session.commit()
        return redirect(url_for('puppies.list'))
    return render_template('add.html',form=form)

@puppies_blueprint.route('/list')
@login_required
def list():
    puppy_list = Puppy.query.all()
    return render_template('list.html',puppies=puppy_list)

@puppies_blueprint.route('/delete',methods=['GET','POST'])
@login_required
def delete():

    form = Del()

    if form.validate_on_submit():
        id_num = form.id.data
        id_to_del = Puppy.query.get(id_num)
        db.session.delete(id_to_del)
        db.session.commit()
        return redirect(url_for('puppies.list'))
    return render_template('delete.html',form=form)

myproject/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Hello, world!</title>
  </head>
  <body>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="{{url_for('index')}}">Home</a>
          <a class="navbar-brand" href="{{url_for('puppies.add')}}">Add</a>
           <a class="navbar-brand" href="{{url_for('owners.add')}}">AddOwner</a>
          <a class="navbar-brand" href="{{url_for('puppies.delete')}}">Delete</a>
          <a class="navbar-brand" href="{{url_for('puppies.list')}}">List</a>
           {% if current_user.is_authenticated %}
              <a class="navbar-brand" href="{{url_for('logout')}}">Logout</a>
           {% else %}
             <a class="navbar-brand" href="{{url_for('login')}}">Login</a>
             <a class="navbar-brand" href="{{url_for('register')}}">Register</a>
           {% endif %}
       </nav>
       <div class="container">
           {% block content %}

           {% endblock %}
       </div>
  </body>
</html>

myproject/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
<h1> This is home page</h1>
</div>
{% endblock %}

myproject/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
<form method="POST">
    {{ form.hidden_tag() }}
    {{ form.username.label }} <br> {{ form.username(class="form-control form-control-lg",placeholder="Username") }}
    <br>
    {{ form.password.label }} <br> {{ form.password(class="form-control form-control-lg",placeholder="Password") }}
    <br>
    <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
    </div>
</form>
</div>
{% endblock %}

myproject/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
<form method="POST">
    {{ form.hidden_tag() }}
    {{ form.username.label }} <br> {{ form.username(class="form-control form-control-lg",placeholder="Username") }}
    <br>
    {{ form.password.label }} <br> {{ form.password(class="form-control form-control-lg",placeholder="Password") }}
    <br>
    {{ form.pass_confirm.label }} <br> {{ form.pass_confirm(class="form-control form-control-lg",placeholder="Confirm Password") }}
    <br>
    <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
    </div>
</form>
</div>
{% endblock %}